
CREATE TABLE IF NOT EXISTS world_state (
    id INTEGER PRIMARY KEY,
    turn_count INTEGER DEFAULT 0,
    width INTEGER DEFAULT 50,
    height INTEGER DEFAULT 50
);
CREATE TABLE IF NOT EXISTS entities (
    id INTEGER PRIMARY KEY AUTOINCREMENT,

    x INTEGER NOT NULL,
    y INTEGER NOT NULL,

    type TEXT NOT NULL,
    color TEXT NOT NULL,

    energy INTEGER DEFAULT 100,
    age INTEGER DEFAULT 0
);